exports.HttpCodes = {
    NOT_FOUND: 'NOT_FOUND',
    BAD_REQUEST: 'BAD_REQUEST',
    FORBIDDEN: 'FORBIDDEN',
    UNAUTHENTICATED: 'UNAUTHENTICATED',
    UNAUTHENTICATED: 'UNAUTHENTICATED',
    CONFLICT: 'CONFLICT',
    BAD_GATEWAY: 'BAD_GATEWAY',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR'
}